### ISSUE TITLE
h3

### ISSUE THREAD

**Issue by citymobil-soloukhin** [keplergl/kepler.gl-tableau#15]
Hi!

How can I set h3_index for kepler.gl in tableau?

**Comment by demartsc** [comment]
Hi @citymobil-soloukhin! 

You can pass the h3 index from tableau data to Kepler.gl. However, I think there is work being done in Kepler.gl itself related to h3 index layer that could effect our plug-in within Tableau. But the bottom line is that it should work the same whether you are using Kepler.gl directly vs tableau extension. For example, the team is doing [work in Kepler to allow you to aggregate by hex id](https://github.com/keplergl/kepler.gl/issues/394) directly within Kepler (vs having to pre-aggregate data before Kepler. cc @heshan0131

**Comment by demartsc** [comment]
@citymobil-soloukhin can you confirm you got what you need here? I will close the issue next week unless there is something else missing. Thanks!

**Comment by citymobil-soloukhin** [comment]
Yes. Thank you
