### ISSUE TITLE
Workbook constantly reloading

### ISSUE THREAD

**Issue by sablastik** [keplergl/kepler.gl-tableau#21]
Hi!

Some users with Viewer Role are seeing an issue in Tableau server 2020.1 where this extension get into an endless loop when trying to load. It appears to get an http 401 (Unauthorized) error when posting to the command: save-add-in-settings

![image](https://user-images.githubusercontent.com/16276988/78969871-b5528a00-7b10-11ea-9308-c0ade3b05542.png)

**Comment by demartsc** [comment]
I think we have seen this when a "Viewer" server user is accessing a view that does not have `readonly` configuration set to true. If you are not in readonly mode there are processes in extension which are trying to "save state" of where you are in the view. Also the bugs we did find related to readonly config were fixed via https://github.com/keplergl/kepler.gl-tableau/pull/14. If you are working on current build and have readonly configured and still see this message, please let us know.

**Comment by sablastik** [comment]
I suppose we work on current build. We take it from https://extensiongallery.tableau.com/extensions/108
and use https://keplergl-tableau.netlify.com for Tableau Server

**Comment by demartsc** [comment]
Yes that should be current build, are you still seeing this issues if the view has been set to read-only? I just tested this on an instance of server as well and was able to view a workbook that had the extension running in read only mode with standard Viewer permissions on Tableau Server.

**Comment by demartsc** [comment]
Closing this issue after no response, assuming read-only mode solved this issue.
