### ISSUE TITLE
Tableau Kepler.gl Extension,

### ISSUE THREAD

**Issue by bashiiiwa** [keplergl/kepler.gl-tableau#23]

**Comment by bashiiiwa** [comment]
I'm trying to use Kepler.gl - Tableau Extension , but after clicking green configure button, nothing happens. Are there any advice ? Windows 10 / Tableau Desktop 2020.1 .

**Comment by cpicco** [comment]
I noticed the exact same behavior in 2020.1 on MacOS

**Comment by demartsc** [comment]
Hi All, thanks for reporting this to us. We are looking into it and will circle back with you. Stay tuned! Also bashiiwa, Kepler.gl leverages WebGL which Tableau Desktop does not support on Windows, so even after figuring out what is going one with this comment,  you still will not be able to leverage the extension within Desktop on a windows machine. Keep bugging Tableau on the existing issue https://github.com/tableau/extensions-api/issues/149 to help push for enablement of WebGL on Windows desktop. Thanks!

**Comment by demartsc** [comment]
Thanks for calling this out @cpicco and @bashiiiwa . Seems that netlify changed their URLs and that impacted us. We have addresses the issue and updated the trex file on the extension gallery. If you grab the latest file from there (and update your server whitelist if need be) you should be good to go. Closing this out for now.
