### ISSUE TITLE
Cannot render points

### ISSUE THREAD

**Issue by bellowswang** [keplergl/kepler.gl-tableau#36]
The same problem reported in https://github.com/keplergl/kepler.gl/issues/827 still exists in kepler.gl-tableau.
Based on my sheet including all the data points with lon and lat, I can display all the types (hexbin, cluster, heatmap, etc.) except point. Actually I can even add labels for points. Then all the labels would be visualized at the correct positions. The time filter also contains a histogram of data.

**Comment by demartsc** [comment]
duplicate to https://github.com/keplergl/kepler.gl-tableau/issues/33
